name: Publish JD
on: ["pull_request", "push"]

env:
  DEST_DIR: _out
  PYTHON_VERSION: "3.10"

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v3"
      - name: "setup python ${{ env.PYTHON_VERSION }}"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: "pip"
      - name: "install dependencies"
        run: |
          pipx install poetry
          pushd _generator
          poetry install
      - name: "generate site"
        run: |
          pushd _generator
          poetry run generate-jd ../$DEST_DIR --metadata ../metadata.yaml --jd-root ..
      - name: "publish"
        if: "${{ github.event_name == 'push' && github.ref == 'refs/heads/data' }}"
        uses: "JamesIves/github-pages-deploy-action@v4"
        with:
          branch: "gh-pages"
          folder: "${{ env.DEST_DIR }}"
          single-commit: true


